version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
nuget:
  disable_publish_on_pr: true
build_script:
- ps: ./scripts/build.ps1
test: off
artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  server: https://www.myget.org/F/primepenguin-centrasharp/api/v2/package
  api_key:
    secure: jXdWHOx5j3gdlvz0NgLl9oIFOqQ/ANEcSerzq7o7sWvCkISlh59J4lblckoOezH4
  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  name: production
  api_key:
    secure: FtNb6c+u7kSECRUn/clCWtUcqdfOrIeEUOUrnNLmAyAQmviWKkvRS5LTuG6fV+OE
  on:
    branch: master
    appveyor_repo_tag: true
