version: 0.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
build_script:
- ps: ./scripts/build.ps1
environment:
  APPVEYOR_REPO_TAG: true
artifacts:
- path: CentraSharp/bin/Release/netstandard1.4
  name: netstandard16
- path: CentraSharp/bin/Release/net45
  name: net461
skip_commits:
  message: /\[skip\]/
  files:
    - readme.md
    - LICENSE
    - .gitignore
    - .vscode/*
    - changelog.md
deploy:
- provider: NuGet
  api_key:
      secure: rKMx/GMvHjSKWMkjOr2Bzo+ht7il6JXI0lJdtBhVVaEqCMsv28lXrDGT7tqIFMNq
  on:
    branch: master
