version: 0.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
build_script:
- ps: ./scripts/build.ps1
artifacts:
- path: StarwebSharp/bin/Release/netstandard1.4
  name: netstandard16
- path: StarwebSharp/bin/Release/net45
  name: net461
skip_commits:
  message: /\[skip\]/
  files:
    - readme.md
    - LICENSE
    - .gitignore
    - .vscode/*
    - changelog.md
deploy:
- provider: NuGet
  server: https://www.myget.org/F/primepenguin-centrasharp/api/v2/package
  api_key:
    secure: jXdWHOx5j3gdlvz0NgLl9oIFOqQ/ANEcSerzq7o7sWvCkISlh59J4lblckoOezH4
  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  api_key:
    secure: tlPfNhypRf0lu3Um0kn7l7dUCycV7sYxbJc5c6ZEVtGXTGvbN+srQZW7iPJ8o7Ib
 artifact: PrimePenguin.CentraSharp.nupkg
