version: 4.0.{build}
image: Visual Studio 2022
build_script:
- ps: ./scripts/build.ps1
environment:
  APPVEYOR_REPO_TAG: true
artifacts:
- path: QuickbutikSharp/bin/Release/netstandard1.4
  name: netstandard16
- path: QuickbutikSharp/bin/Release/net45
  name: net461
skip_commits:
  message: /\[skip\]/
  files:
    - readme.md
    - LICENSE
    - .gitignore
    - .vscode/*
    - changelog.md
deploy:
- provider: NuGet
  api_key:
      secure: 2Qfm8tq30586MvEqXEwMmpDEyzJG3fdBw/r2kFi0UG/vUEruTXUPBNA0p/EWj7Am
  on:
    branch: master
